### ISSUE TITLE
TFT2.8 Customizable Firmware

### ISSUE THREAD

**Issue by mpallen509** [bigtreetech/BIGTREETECH-TFT2.8#1]
Will customizable firmware for this screen be released? (Similar to the current TFT35 v1.2 firmware)

Having just a .bin file inhibits from further developing smooth printer operation and UI/UX.

**Comment by Msq001** [comment]
https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware
here have released the source code， it contains TFT28.

**Comment by mpallen509** [comment]
@Msq001 Thanks for the link. I will look into it further.

**Comment by A-SLVV** [comment]
it doesn't work. Only flashes this firmware and no other: https://github.com/bigtreetech/BIGTREETECH-TFT2.8/tree/master/firmware

Tried to compile this https://github.com/bigtreetech/BIGTREETECH-TouchScreenFirmware for various builds: TFT28 1.0, TFT28 v3, MSK 28, TFT35. Nothing was accepted by the screen.
